name: exception_handler
description: A Flutter package that automatically detects and reports app exceptions via email, enhancing error tracking and debugging processes.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.3"

dependencies:
  connectivity_plus: ^6.1.0
  device_info_plus: ^10.1.2
  flutter:
    sdk: flutter
  logger: ^2.4.0
  mailer: ^6.2.0
  network_info_plus: ^6.1.1
  package_info_plus: ^8.1.1
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  very_good_analysis: ^3.1.0
