name: exception_handler
description: A Flutter package that automatically detects and reports app exceptions via email, enhancing error tracking and debugging processes.
version: 1.0.0

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=3.7.0"

dependencies:
  connectivity_plus: ^3.0.6
  device_info_plus: ^8.2.2
  flutter:
    sdk: flutter
  logger: ^1.4.0
  mailer: ^6.1.2
  package_info_plus: ^3.1.2
  path: ^1.8.0
  path_provider: ^2.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  very_good_analysis: ^3.1.0
